#!/bin/sh

bundle install --binstubs > /dev/null 2>&1

function bundle() {
  echo 'ERROR: Should not have called `bundle exec`.'
}

export -f bundle


vim +6 -u vimrc -c 'silent call vroom#RunNearestTest()' -c 'q' spec/some_class_spec.rb 2>&- | grep '1 example, 0 failures' | sed 's/.*/Success/'
